server:
  port: 8090

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/education?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
  mvc:
    static-path-pattern: /static/**

mybatis:
  type-aliases-package: com.van589.mooc.domain
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      van589:
        mooc:
          web:
            admin:
              dao: debug